<?php

namespace OC\AuthBundle\Repository;

/**
 * evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class evenementRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findEvenement($id)
    {
        if( !empty($id)||!isset($id))
        {
            $evenement = $this->createQueryBuilder('e')
            ->innerJoin('e.present2s','pre')
            ->addSelect('pre')
            ->Where('pre.Evenement = :id')
            ->setParameter('id',$id);
           return $evenement->getQuery()
                     ->getResult();
        
        }
    }
}
