<?php

namespace OC\AuthBundle\Repository;

/**
 * PresentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getJourEvenement($Idevenement)
    {
       $qb = $this->createQueryBuilder('p')
                ->innerJoin('p.Evenement','eve')
                ->addSelect('eve')
                ->where('eve.id=:id')
                ->setParameter('id',$Idevenement);
                return $qb;
    }
    
   
    
   
}
